//
//  DataDeclaration.swift
//  moonshot
//
//  Created by Adam on 27/04/2026.
//

import Foundation
import MapKit

enum SortType: String, CaseIterable {
    case alphabetical
    case duration
    case spacewalks
}


            

let splashdownPrograms = ["Mercury", "Gemini", "Apollo", "Apollo Applications", "Commercial Crew", "Artemis"]
let landingPrograms = ["Space Shuttle", "Shenzhou", "Vostok","Voskhod", "Soyuz", "Soyuz-T", "Soyuz-TM" ,"Soyuz-TMA","Soyuz-MS"]
let spaceProgramsUSA = ["Mercury", "Gemini", "Apollo", "Apollo Applications", "Space Shuttle", "Commercial Crew", "Artemis"]
let orderedKey = spaceProgramsUSA

let spaceProgramsRU = ["Vostok","Voskhod", "Soyuz", "Soyuz-T", "Soyuz-TM" ,"Soyuz-TMA","Soyuz-MS"]


// flags
let countryToFlag: Dictionary<String, String> = [
    
    "VIE":"🇻🇳",
    "USA":"🇺🇸",
    "UKR":"🇺🇦",
    "UAE":"🇦🇪",
    "GBR":"🇬🇧",
    "SYR":"🇸🇾",
    "SUI":"🇨🇭",
    "SWE":"🇸🇪",
    "ESP":"🇪🇸",
    "KOR":"🇰🇷",
    "ZAR":"🇿🇦",
    "SLO":"🇸🇮",
    "SVK":"🇸🇰",
    "RUS":"🇷🇺",
    "USSR":"☭",
    "ROM":"🇷🇴",
    "POL":"🇵🇱",
    "NED":"🇳🇱",
    "MON":"🇲🇳",
    "MEX":"🇲🇽",
    "MAL":"🇲🇾",
    "JAP":"🇯🇵",
    "ITA":"🇮🇹",
    "ISR":"🇮🇱",
    "IND":"🇮🇳",
    "HUN":"🇭🇺",
    "DEU":"🇩🇪",
    "GDR":"🇩🇪☭",
    "FRG":"🇩🇪",
    "FRA":"🇫🇷",
    "DEN":"🇩🇰",
    "CUB":"🇨🇺",
    "CNA":"🇨🇳",
    "CAN":"🇨🇦",
    "BUL":"🇧🇬",
    "BRA":"🇧🇷",
    "BGM":"🇧🇪",
    "BLR":"🇧🇾",
    "AUT":"🇦🇹",
    "AFG":"🇦🇫"
]

let spareCountryToFlagDict: [(String, String)] = [
 ("Zimbabwe","🇿🇼"),
("Zambia","🇿🇲"),
("Yemen","🇾🇪"),
("Venezuela","🇻🇪"),
("Vatican City","🇻🇦"),
("Uzbekistan","🇺🇿"),
("Uruguay","🇺🇾"),
("Uganda","🇺🇬"),
("Turkmenistan","🇹🇲"),
("Turkey","🇹🇷"),
("Tunisia","🇹🇳"),
("Trinidad and Tobago","🇹🇹"),
("Tonga","🇹🇴"),
("Togo","🇹🇬"),
("Thailand","🇹🇭"),
("Tanzania","🇹🇿"),
("Tajikistan","🇹🇯"),
("Taiwan","🇹🇼"),
("Suriname","🇸🇷"),
("Sudan","🇸🇩"),
("Sri Lanka","🇱🇰"),
("South Sudan","🇸🇸"),
("Somalia","🇸🇴"),
("Solomon Islands","🇸🇧"),
("Singapore","🇸🇬"),
("Sierra Leone","🇸🇱"),
("Seychelles","🇸🇨"),
("Serbia","🇷🇸"),
("Senegal","🇸🇳"),
("Saudi Arabia","🇸🇦"),
("Sao Tome and Principe","🇸🇹"),
("San Marino","🇸🇲"),
("Samoa","🇼🇸"),
("Saint Lucia","🇱🇨"),
("Rwanda","🇷🇼"),
("Qatar","🇶🇦"),
("Portugal","🇵🇹"),
("Philippines","🇵🇭"),
("Peru","🇵🇪"),
("Paraguay","🇵🇾"),
("Papua New Guinea","🇵🇬"),
("Panama","🇵🇦"),
("Palestine","🇵🇸"),
("Pakistan","🇵🇰"),
("Oman","🇴🇲"),
("Norway","🇳🇴"),
("North Korea","🇰🇵"),
("Nigeria","🇳🇬"),
("Niger","🇳🇪"),
("Nicaragua","🇳🇮"),
("New Zealand","🇳🇿"),
("Nepal","🇳🇵"),
("Namibia","🇳🇦"),
("Myanmar","🇲🇲"),
("Mozambique","🇲🇿"),
("Morocco","🇲🇦"),
("Montenegro","🇲🇪"),
("Monaco","🇲🇨"),
("Moldova","🇲🇩"),
("Mauritius","🇲🇺"),
("Mauritania","🇲🇷"),
("Malta","🇲🇹"),
("Mali","🇲🇱"),
("Maldives","🇲🇻"),
("Malawi","🇲🇼"),
("Madagascar","🇲🇬"),
("Luxembourg","🇱🇺"),
("Lithuania","🇱🇹"),
("Liechtenstein","🇱🇮"),
("Libya","🇱🇾"),
("Liberia","🇱🇷"),
("Lesotho","🇱🇸"),
("Lebanon","🇱🇧"),
("Latvia","🇱🇻"),
("Laos","🇱🇦"),
("Kyrgyzstan","🇰🇬"),
("Kuwait","🇰🇼"),
("Kosovo","🇽🇰"),
("Kenya","🇰🇪"),
("Kazakhstan","🇰🇿"),
("Jordan","🇯🇴"),
("Jamaica","🇯🇲"),
("Ireland","🇮🇪"),
("Iraq","🇮🇶"),
("Iran","🇮🇷"),
("Indonesia","🇮🇩"),
("Iceland","🇮🇸"),
("Honduras","🇭🇳"),
("Haiti","🇭🇹"),
("Guyana","🇬🇾"),
("Guinea-Bissau","🇬🇼"),
("Guinea","🇬🇳"),
("Guatemala","🇬🇹"),
("Grenada","🇬🇩"),
("Greece","🇬🇷"),
("Ghana","🇬🇭"),
("Georgia","🇬🇪"),
("Gambia","🇬🇲"),
("Gabon","🇬🇦"),
("Finland","🇫🇮"),
("Fiji","🇫🇯"),
("Ethiopia","🇪🇹"),
("Estonia","🇪🇪"),
("Eritrea","🇪🇷"),
("Equatorial Guinea","🇬🇶"),
("El Salvador","🇸🇻"),
("Egypt","🇪🇬"),
("Ecuador","🇪🇨"),
("Dominican Republic","🇩🇴"),
("Dominica","🇩🇲"),
("Djibouti","🇩🇯"),
("Czechia","🇨🇿"),
("Cyprus","🇨🇾"),
("Croatia","🇭🇷"),
("Costa Rica","🇨🇷"),
("DR Congo","🇨🇩"),
("Rep. Congo","🇨🇬"),
("Comoros","🇰🇲"),
("Colombia","🇨🇴"),
("Chile","🇨🇱"),
("Chad","🇹🇩"),
("Central African Republic","🇨🇫"),
("Cameroon","🇨🇲"),
("Cambodia","🇰🇭"),
("Burundi","🇧🇮"),
("Burkina Faso","🇧🇫"),
("Brunei","🇧🇳"),
("Botswana","🇧🇼"),
("Bosnia and Herzegovina","🇧🇦"),
("Bolivia","🇧🇴"),
("Bhutan","🇧🇹"),
("Benin","🇧🇯"),
("Belize","🇧🇿"),
("Barbados","🇧🇧"),
("Bangladesh","🇧🇩"),
("Bahrain","🇧🇭"),
("Bahamas","🇧🇸"),
("Azerbaijan","🇦🇿"),
("Australia","🇦🇺"),
("Armenia","🇦🇲"),
("Argentina","🇦🇷"),
("Antigua and Barbuda","🇦🇬"),
("Angola","🇦🇴"),
("Andorra","🇦🇩"),
("Algeria","🇩🇿"),
("Albania","🇦🇱"),
("Cabo Verde", "🇨🇻"),
("Eswatini", "🇸🇿"),
("Kiribati", "🇰🇮"),
("Marshall Islands", "🇲🇭"),
("Micronesia", "🇫🇲"),
("Nauru", "🇳🇷"),
("Palau", "🇵🇼"),
("Saint Kitts and Nevis", "🇰🇳"),
("Saint Vincent and the Grenadines", "🇻🇨"),
("England","🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
("Scotland","🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
("Wales","🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
("Sark", "🇨🇶"),
("Jersey", "🇯🇪"),
("Guernsey","🇬🇬"),
("Isle of Man","🇮🇲"),
("South Georgia", "🇬🇸"),
("Åland Islands","🇦🇽"),
("Wallis and Futuna","🇼🇫"),
("U.S. Virgin Islands","🇻🇮"),
("Turks and Caicos Islands","🇹🇨"),
("Sint Maarten","🇸🇽"),
("Saint Pierre and Miquelon","🇵🇲"),
("Réunion","🇷🇪"),
("Puerto Rico","🇵🇷"),
("Northern Mariana Islands","🇲🇵"),
("Norfolk Island","🇳🇫"),
("Niue","🇳🇺"),
("New Caledonia","🇳🇨"),
("Montserrat","🇲🇸"),
("Martinique","🇲🇶"),
("Guam","🇬🇺"),
("Guadeloupe","🇬🇵"),
("Greenland","🇬🇱"),
("Gibraltar","🇬🇮"),
("French Polynesia","🇵🇫"),
("French Guiana","🇬🇫"),
("Faroe Islands","🇫🇴"),
("Falkland Islands","🇫🇰"),
("Curaçao","🇨🇼"),
("Cook Islands","🇨🇰"),
("Christmas Island","🇨🇽"),
("Cayman Islands","🇰🇾"),
("British Virgin Islands","🇻🇬"),
("British Indian Ocean Territory","🇮🇴"),
("Bermuda","🇧🇲"),
("Aruba","🇦🇼"),
("American Samoa","🇦🇸"),
("Anguilla","🇦🇮"),
("Hong Kong","🇭🇰"),
("European Union","🇪🇺"),
("Macau", "🇲🇴"),
("Antarctica", "🇦🇶"),
("Anguilla", "🇦🇮"),
("Cocos Islands","🇨🇨"),
("Guam","🇬🇺"),
("Canary Islands", "🇮🇨"),
("Mayotte","🇾🇹"),
("Pitcairn Islands", "🇵🇳"),
("French Guyana","🇬🇫"),
("French Southern and Antarctic Lands", "🇹🇫"),
("Tokelau","🇹🇰"),
("Aruba", "🇦🇼"),
("Bonaire", "🇧🇶"),
("Saint Barthélemy", "🇧🇱"),
("Saint Helena", "🇸🇭"),
("Ascension Island", "🇦🇨"),
("Tristan da Cunha", "🇹🇦"),
("Western Sahara", "🇪🇭"),
("Northern Ireland", "🏳️")
]

// cases where spaceship is 1 mission only and patch needs to be inverted color
let missionShipsToInvert = ["Soyuz 1","Soyuz 2","Soyuz 4","Soyuz 5","Soyuz 6","Soyuz 7","Soyuz 8","Soyuz 9","Soyuz 10","Soyuz 11","Soyuz 12","Soyuz 13","Soyuz 14","Soyuz 15","Soyuz 17","Soyuz 18","Soyuz 18a","Soyuz 19","Soyuz 20","Soyuz 21","Soyuz 22","Soyuz 23","Soyuz 24","Soyuz 25","Soyuz 26","Soyuz 27","Soyuz 28","Soyuz 29","Soyuz 32","Soyuz 34","Soyuz 35","Soyuz MS-01","Soyuz MS-02","Soyuz MS-03","Soyuz MS-04","Soyuz MS-05","Soyuz MS-06","Soyuz MS-07","Soyuz MS-08","Soyuz MS-09","Soyuz MS-10","Soyuz MS-11","Soyuz MS-12","Soyuz MS-13","Soyuz MS-14","Soyuz MS-15","Soyuz MS-16","Soyuz MS-17","Soyuz MS-18","Soyuz MS-19","Soyuz MS-20","Soyuz MS-21","Soyuz MS-22","Soyuz MS-23","Soyuz MS-24","Soyuz MS-25","Soyuz MS-26","Soyuz MS-27","Soyuz MS-28","Soyuz MS-29","Soyuz T-1","Soyuz T-2","Soyuz T-3","Soyuz T-4","Soyuz T-5","Soyuz T-7","Soyuz T-8","Soyuz T-9","Soyuz T-10","Soyuz T-10-1","Soyuz T-12","Soyuz T-13","Soyuz T-14","Soyuz T-15","Soyuz TM-2","Soyuz TM-4","Soyuz TM-8","Soyuz TM-9","Soyuz TM-10","Soyuz TMA-01M","Soyuz TMA-02M","Soyuz TMA-03M","Soyuz TMA-04M","Soyuz TMA-05M","Soyuz TMA-6","Soyuz TMA-06M","Soyuz TMA-7","Soyuz TMA-07M","Soyuz TMA-8","Soyuz TMA-08M","Soyuz TMA-9","Soyuz TMA-09M","Soyuz TMA-10","Soyuz TMA-10M","Soyuz TMA-11","Soyuz TMA-11M","Soyuz TMA-12","Soyuz TMA-12M","Soyuz TMA-13","Soyuz TMA-13M","Soyuz TMA-14","Soyuz TMA-14M","Soyuz TMA-15","Soyuz TMA-15M","Soyuz TMA-16","Soyuz TMA-16M","Soyuz TMA-17","Soyuz TMA-17M","Soyuz TMA-18","Soyuz TMA-18M","Soyuz TMA-19","Soyuz TMA-19M","Soyuz TMA-20","Soyuz TMA-20M","Soyuz TMA-21","Voskhod 1","Voskhod 2","Vostok 1","Vostok 2","Vostok 3","Vostok 4","Vostok 5","Vostok 6"]
